### ISSUE TITLE
add ReadRes monad transformer?

### ISSUE THREAD

**Issue by ihor-rud** [stefan-hoeck/idris2-uv#31]
I've been playing with this library for some time and found operations such as `Async es (ReadRes a) -> Async es (ReadRes b)` to be quite common in my code. Adding a `ReadResT` transformer should make code simpler. I can prepare a mr with `ReadResT` implementation, but before doing that, I want to make sure that this is the best solution for this problem.

**Comment by stefan-hoeck** [comment]
I'm open to such a PR. I hardly ever use monad transformers in my own Idris code, but others might find them useful as well.

**Comment by stefan-hoeck** [comment]
Implemented in #32
